import { env } from '../config/env.js';
import { log } from '../logger.js';

export class SlackTool {
  constructor() {
    this.webhookUrl = env.SLACK_WEBHOOK_URL;
    this.enabled = !!this.webhookUrl;

    if (!this.enabled) {
      log('SLACK', 'Slack webhook URL not configured — notifications disabled', 'WARN');
    }
  }

  async sendMessage(message) {
    if (!this.enabled) {
      log('SLACK', 'Slack disabled: no webhook URL configured');
      return { sent: false, reason: 'Slack webhook URL not configured' };
    }

    log('SLACK', 'Sending message to Slack');

    try {
      const response = await fetch(this.webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: message }),
      });

      if (!response.ok) {
        const text = await response.text();
        throw new Error(`Slack API responded with ${response.status}: ${text}`);
      }

      log('SLACK', 'Message sent successfully');
      return { sent: true };
    } catch (error) {
      log('SLACK', `Failed to send message: ${error.message}`, 'ERROR');
      throw new Error(`Slack notification failed: ${error.message}`);
    }
  }

  async sendMeetingSummary(meetingData) {
    const blocks = [
      {
        type: 'header',
        text: { type: 'plain_text', text: `📋 Meeting Summary: ${meetingData.title}`, emoji: true },
      },
      { type: 'divider' },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: `*Date:* ${meetingData.date}\n*Participants:* ${(meetingData.participants || []).join(', ') || 'Not specified'}` },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: `*Summary:*\n${meetingData.summary}` },
      },
    ];

    if (meetingData.keyPoints && meetingData.keyPoints.length > 0) {
      const points = meetingData.keyPoints.map((p, i) => `${i + 1}. ${p}`).join('\n');
      blocks.push({ type: 'section', text: { type: 'mrkdwn', text: `*Key Discussion Points:*\n${points}` } });
    }

    if (meetingData.decisions && meetingData.decisions.length > 0) {
      const decisions = meetingData.decisions.map(d => `• ${d}`).join('\n');
      blocks.push({ type: 'section', text: { type: 'mrkdwn', text: `*Decisions:*\n${decisions}` } });
    }

    if (meetingData.actionItems && meetingData.actionItems.length > 0) {
      const items = meetingData.actionItems.map(a =>
        `• *${a.task}* — Owner: ${a.owner || 'Not assigned'} | Deadline: ${a.deadline || 'Not set'}`
      ).join('\n');
      blocks.push({ type: 'section', text: { type: 'mrkdwn', text: `*Action Items:*\n${items}` } });
    }

    if (meetingData.risksBlockers && meetingData.risksBlockers.length > 0) {
      const risks = meetingData.risksBlockers.map(r => `• ${r}`).join('\n');
      blocks.push({ type: 'section', text: { type: 'mrkdwn', text: `*Risks & Blockers:*\n${risks}` } });
    }

    blocks.push({ type: 'divider' });
    blocks.push({
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `🤖 Generated by Groovy's AI Meeting Agent` }],
    });

    return this._sendBlocks(blocks);
  }

  async sendActionItems(actionItemsData) {
    const blocks = [
      {
        type: 'header',
        text: { type: 'plain_text', text: '✅ Action Items', emoji: true },
      },
      { type: 'divider' },
    ];

    for (const meeting of actionItemsData) {
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `*From: ${meeting.meetingTitle}* (${meeting.meetingDate})` },
      });

      if (meeting.actionItems && meeting.actionItems.length > 0) {
        for (const item of meeting.actionItems) {
          const owner = item.owner && item.owner !== 'Not specified' ? item.owner : 'Unassigned';
          const deadline = item.deadline && item.deadline !== 'Not specified' ? item.deadline : 'No deadline';
          blocks.push({
            type: 'section',
            text: { type: 'mrkdwn', text: `• *${item.task}*\n    👤 ${owner}  |  🗓 ${deadline}` },
          });
        }
      }
    }

    blocks.push({ type: 'divider' });
    blocks.push({
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `🤖 Generated by Groovy's AI Meeting Agent` }],
    });

    return this._sendBlocks(blocks);
  }

  async sendDecisions(decisions) {
    if (!decisions || decisions.length === 0) {
      return this.sendMessage('No decisions were recorded in this meeting.');
    }

    const lines = decisions.map(d => `• ${d}`).join('\n');
    const message = `*Groovy Meeting Decisions* :judge:\n${lines}`;

    return this.sendMessage(message);
  }

  async _sendBlocks(blocks) {
    if (!this.enabled) {
      log('SLACK', 'Slack disabled: no webhook URL configured');
      return { sent: false, reason: 'Slack webhook URL not configured' };
    }

    log('SLACK', 'Sending rich message to Slack');

    try {
      const response = await fetch(this.webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ blocks }),
      });

      if (!response.ok) {
        const text = await response.text();
        throw new Error(`Slack API responded with ${response.status}: ${text}`);
      }

      log('SLACK', 'Rich message sent successfully');
      return { sent: true };
    } catch (error) {
      log('SLACK', `Failed to send rich message: ${error.message}`, 'ERROR');
      throw new Error(`Slack notification failed: ${error.message}`);
    }
  }
}
